fix: Added missing cassert header (#4768)
While building `acts` for CMS offline software, using newer Eigen, we got build errors like [a]. This PR proposes to add the missing `cassert`.

[a]
```
/data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc13/external/acts/v44.0.1-2ad8ea44d9e685319e883d7197260aee/acts-v44.0.1/Core/include/Acts/Utilities/VectorHelpers.hpp: In function 'std::array<double, 4> Acts::VectorHelpers::evaluateTrigonomics(const Acts::Vector3&)':
/data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc13/external/acts/v44.0.1-2ad8ea44d9e685319e883d7197260aee/acts-v44.0.1/Core/include/Acts/Utilities/VectorHelpers.hpp:154:3: error: 'assert' was not declared in this scope
  154 |   assert(sinTheta != 0 &&
      |   ^~~~~~
/data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc13/external/acts/v44.0.1-2ad8ea44d9e685319e883d7197260aee/acts-v44.0.1/Core/include/Acts/Utilities/VectorHelpers.hpp:20:1: note: 'assert' is defined in header '<cassert>'; did you forget to '#include <cassert>'?
   19 | #include "Eigen/Dense"
  +++ |+#include <cassert>
   20 | 
In file included from /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc13/external/acts/v44.0.1-2ad8ea44d9e685319e883d7197260aee/acts-v44.0.1/Core/src/EventData/TrackParameterHelpers.cpp:12:
/data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc13/external/acts/v44.0.1-2ad8ea44d9e685319e883d7197260aee/acts-v44.0.1/Core/include/Acts/Utilities/VectorHelpers.hpp: In function 'std::array<double, 4> Acts::VectorHelpers::evaluateTrigonomics(const Acts::Vector3&)':
/data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc13/external/acts/v44.0.1-2ad8ea44d9e685319e883d7197260aee/acts-v44.0.1/Core/include/Acts/Utilities/VectorHelpers.hpp:154:3: error: 'assert' was not declared in this scope
  154 |   assert(sinTheta != 0 &&
      |   ^~~~~~
/data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc13/external/acts/v44.0.1-2ad8ea44d9e685319e883d7197260aee/acts-v44.0.1/Core/include/Acts/Utilities/VectorHelpers.hpp:20:1: note: 'assert' is defined in header '<cassert>'; did you forget to '#include <cassert>'?
   19 | #include "Eigen/Dense"
  +++ |+#include <cassert>
```