refactor: required for new ITk geometry (#1653)
New element names in `buildITkGeometry` for updated ATLAS ITk and HGTD geometry, `ATLAS-P2-RUN4-01-00-00`.
This supports the new geometry TGeo root file just added to the [`acts-itk`](https://gitlab.cern.ch/atlas/acts-itk) repo.

* Note that without this PR, the latest version of `acts-itk` (tag [`ATLAS-P2-RUN4-01-00-00`](https://gitlab.cern.ch/atlas/acts-itk/-/tree/ATLAS-P2-RUN4-01-00-00)) will not work. `acts-itk` tag [`ATLAS-P2-23`](https://gitlab.cern.ch/atlas/acts-itk/-/tree/ATLAS-P2-23) can be used instead.

* With this PR, `acts-itk` [`master`](https://gitlab.cern.ch/atlas/acts-itk) (or tag [`ATLAS-P2-RUN4-01-00-00`](https://gitlab.cern.ch/atlas/acts-itk/-/tree/ATLAS-P2-RUN4-01-00-00)) should be used.

* The error message from `itk.py` indicating a version mismatch is:
```
ValueError: Incorrect binning configuration found: Number of configurations does not match number of protolayers in subvolume Pixel::Pixel. Quitting.
```