fix: hash_root_file AttributeError: no field named 'to_numpy' (#1129)
With my installation
```
ROOT_HASH_CHECKS=on pytest
```
fails with errors like
```
FAILED src/Examples/Python/tests/test_examples.py::test_particle_gun - AttributeError: no field named 'to_numpy'
/cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/awkward/highlevel.py:1123: AttributeError
```
I'm using `LCG_101` which has Python 3.9 and `awkward` 1.0.2. It seems that `obj.to_numpy()` is not supported in this version, but `awkward.to_numpy(obj)` is.

Can someone advise whether this is likely OK for other installations?