fix: Do not use requires in class EDM definition (#3731)
It looks like this is creating issues in Athena with
```console
In file included from libActsEventDict dictionary payload:146:
In file included from /cvmfs/atlas-nightlies.cern.ch/repo/sw/main--ACTS_Athena_x86_64-el9-gcc13-opt/2024-10-09T2101/Athena/25.0.20/InstallArea/x86_64-el9-gcc13-opt/include/ActsEvent/Seed.h:8:
/cvmfs/atlas-nightlies.cern.ch/repo/sw/main--ACTS_Athena_x86_64-el9-gcc13-opt/2024-10-09T2101/AthenaExternals/25.0.20/InstallArea/x86_64-el9-gcc13-opt/include/Acts/Acts/EventData/Seed.hpp:17:11: error: requires clause differs in template redeclaration
  requires(N >= 3ul)
          ^
Forward declarations from /cvmfs/atlas-nightlies.cern.ch/repo/sw/main--ACTS_Athena_x86_64-el9-gcc13-opt/2024-10-09T2101/Athena/25.0.20/InstallArea/x86_64-el9-gcc13-opt/lib/Athena.rootmap:773:18: note: previous template declaration is here
namespace Acts { template <typename external_spacepoint_t, size_t> class Seed; }
```

/cc @krasznaa 

@Ragansu and @Corentin-Allaire managed to make it work by:
> removed requires(N >= 3ul) in Seed.h and Seed.ipp and recompiled ACTS
> commented out parts in CxxUtils.h which delt with std::range when __cling__ is enabled. and recompiled Athena with a modified Package Filter.

Quoting:
> For information I think part of the issue might be that Cling doesn't like the requiere in the seed definition:
> The other issue seem to be that athena redefine the std::range::end function when Cling is used (in CxxUtils/range). Probably because it was not implemented before, but now this create a conflict with newer root version I guess ?  

See: https://atlas-art-data.web.cern.ch/atlas-art-data/grid-output/main/Athena/x86_64-el9-gcc13-opt/2024-10-08T2101/InDetPhysValMonitoring/test_run4_acts_vertex_PU200/tarball_logs/payload.stdout 

Co-authored-by: Pierfrancesco Butti <25535240+pbutti@users.noreply.github.com>